theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: <p align="center">Johnny Le </p>

logo: assets/JohnnyProfile.jpeg

description: 
 <p align="center">
  <a href="https://sites.uci.edu/janglab/">Dr. Cholsoon Jang Laboratory</a> |
  <a href="https://scholar.google.com/citations?user=veVhHrkAAAAJ&hl=en&oi=ao">Google Scholar</a>
  </p>

  <p align="justify">
  I am pursuing a MD/PhD at the University of California, Irvine. 

  <br><br>
  My thesis project involves studying fat and skin metabolism utilizing state-of-the-art mass spectrometry and stable isotope tracing. 

show_downloads: false
